spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:postgresql://localhost:5433/healthpay
    username: admin
    password: "123456test@jkaH"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: appointmentCreated:com.healthpay.appointment_service.event.AppointmentCreatedEvent
    consumer:
      group-id: appointment-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: paymentProcessed:com.healthpay.appointment_service.event.PaymentProcessedEvent
